import React, { useState, useEffect, Suspense, lazy } from "react";
import { Sparkles, ArrowRight, Calculator } from "lucide-react";
import { ArticleCategory, ArticlePost, Comment, SiteSettings, AdminUser } from "./types";
import {
  getAllPosts,
  getInitialPosts,
  savePost,
  deletePost,
  incrementPostViews,
  getAllComments,
  getSiteSettings,
  saveSiteSettings,
  getCurrentAdminSession,
  logoutAdmin,
} from "./lib/storage";
import { SEOHead } from "./components/SEOHead";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { ArticleCard } from "./components/ArticleCard";
import { NewsletterSignup } from "./components/NewsletterSignup";

// Code-split heavy components away from initial public visitor bundle
const ArticleReader = lazy(() =>
  import("./components/ArticleReader").then((m) => ({ default: m.ArticleReader }))
);
const AdminDashboard = lazy(() =>
  import("./components/admin/AdminDashboard").then((m) => ({ default: m.AdminDashboard }))
);
const AdminAuthModal = lazy(() =>
  import("./components/admin/AdminAuthModal").then((m) => ({ default: m.AdminAuthModal }))
);
const CalculatorSuitePage = lazy(() =>
  import("./components/CalculatorSuitePage").then((m) => ({ default: m.CalculatorSuitePage }))
);

const CATEGORY_SLUG_MAP: Record<string, ArticleCategory> = {
  "fund-comparison": "Fund Comparison",
  "performance-analysis": "Performance Analysis",
  "market-trends": "Market Trends",
  "category-deep-dive": "Category Deep-Dive",
  "sip-strategies": "SIP Strategies",
};

const CATEGORY_TO_SLUG: Record<ArticleCategory, string> = {
  "Fund Comparison": "fund-comparison",
  "Performance Analysis": "performance-analysis",
  "Market Trends": "market-trends",
  "Category Deep-Dive": "category-deep-dive",
  "SIP Strategies": "sip-strategies",
};

export const CALCULATOR_CONFIG: Record<
  "direct-vs-regular" | "step-up" | "cost-of-delay" | "sip-vs-lumpsum",
  { name: string; title: string; description: string; urlPath: string }
> = {
  "direct-vs-regular": {
    name: "Direct vs Regular Mutual Fund Calculator",
    title: "Direct vs Regular Fund Calculator | YieldNest",
    description: "Calculate how much wealth you lose to distributor commissions and Total Expense Ratio (TER) drag over your SIP tenure in Indian mutual funds.",
    urlPath: "/calculator/direct-vs-regular",
  },
  "step-up": {
    name: "Step-Up SIP Compounding Calculator",
    title: "Step-Up SIP Compounding Calculator | YieldNest",
    description: "Simulate how increasing your monthly SIP by 5% to 25% each year accelerates your mutual fund corpus. Calculate extra wealth generated by annual step-ups.",
    urlPath: "/calculator/step-up-sip",
  },
  "cost-of-delay": {
    name: "Cost of Delay SIP Calculator",
    title: "Cost of Delay SIP Calculator | YieldNest",
    description: "Find out how much money you lose by delaying your mutual fund SIP by 6 months, 1 year, or 2 years. Calculate the compound interest penalty of waiting.",
    urlPath: "/calculator/cost-of-delay",
  },
  "sip-vs-lumpsum": {
    name: "SIP vs Lumpsum Mutual Fund Strategy Comparator",
    title: "SIP vs Lumpsum Calculator | YieldNest",
    description: "Compare mutual fund returns between a one-time lumpsum investment and a staggered monthly SIP over the same time horizon with delta analysis.",
    urlPath: "/calculator/sip-vs-lumpsum",
  },
};

export default function App() {
  const [posts, setPosts] = useState<ArticlePost[]>(() => getInitialPosts());
  const [comments, setComments] = useState<Comment[]>([]);
  const [settings, setSettings] = useState<SiteSettings>(getSiteSettings());
  const [currentCategory, setCurrentCategory] = useState<ArticleCategory | "all">("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedArticle, setSelectedArticle] = useState<ArticlePost | null>(null);
  const [isAdminView, setIsAdminView] = useState(false);
  const [adminInitialTab, setAdminInitialTab] = useState<string>("posts");
  const [adminUser, setAdminUser] = useState<AdminUser | null>(getCurrentAdminSession());
  const [showAuthModal, setShowAuthModal] = useState(false);
  const [loading, setLoading] = useState(false);
  const [isCalculatorView, setIsCalculatorView] = useState(false);
  const [calculatorTab, setCalculatorTab] = useState<"direct-vs-regular" | "step-up" | "cost-of-delay" | "sip-vs-lumpsum">("direct-vs-regular");

  // Initialize and handle URL routing (Instant zero-delay resolution from preloaded state)
  useEffect(() => {
    // Resolve initial route immediately using synchronous baseline (0ms blocking)
    handleRouteFromUrl(posts);

    // Defer background data refresh to idle time to guarantee fast FCP/LCP
    const runBackgroundSync = () => {
      loadData();
    };

    if ("requestIdleCallback" in window) {
      (window as any).requestIdleCallback(runBackgroundSync, { timeout: 2000 });
    } else {
      setTimeout(runBackgroundSync, 600);
    }

    const handlePopState = () => {
      handleRouteFromUrl();
    };
    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, []);

  const loadData = async () => {
    try {
      const loadedPosts = await getAllPosts();
      const loadedComments = await getAllComments();
      const loadedSettings = getSiteSettings();
      setPosts(loadedPosts);
      setComments(loadedComments);
      setSettings(loadedSettings);
      setAdminUser(getCurrentAdminSession());
      // Re-check route with freshly loaded posts in case of deep direct link
      handleRouteFromUrl(loadedPosts);
    } catch (err) {
      console.warn("Background posts sync notice:", err);
    }
  };

  const handleRouteFromUrl = (availablePosts?: ArticlePost[]) => {
    const rawPath = window.location.pathname;
    const path = rawPath.replace(/\/+$/, "") || "/";
    const currentList = availablePosts && availablePosts.length > 0 ? availablePosts : posts;

    // Check for individual calculator dedicated URLs & calculators hub
    if (path === "/calculator/direct-vs-regular" || path === "/calculators/direct-vs-regular") {
      setCalculatorTab("direct-vs-regular");
      setIsCalculatorView(true);
      setSelectedArticle(null);
      setIsAdminView(false);
      return;
    } else if (path === "/calculator/step-up-sip" || path === "/calculators/step-up-sip" || path === "/calculator/step-up" || path === "/calculators/step-up") {
      setCalculatorTab("step-up");
      setIsCalculatorView(true);
      setSelectedArticle(null);
      setIsAdminView(false);
      return;
    } else if (path === "/calculator/cost-of-delay" || path === "/calculators/cost-of-delay") {
      setCalculatorTab("cost-of-delay");
      setIsCalculatorView(true);
      setSelectedArticle(null);
      setIsAdminView(false);
      return;
    } else if (path === "/calculator/sip-vs-lumpsum" || path === "/calculators/sip-vs-lumpsum") {
      setCalculatorTab("sip-vs-lumpsum");
      setIsCalculatorView(true);
      setSelectedArticle(null);
      setIsAdminView(false);
      return;
    } else if (path.startsWith("/calculators") || path.startsWith("/calculator")) {
      const searchParams = new URLSearchParams(window.location.search);
      const tabParam = searchParams.get("tab") as any;
      if (tabParam === "step-up" || tabParam === "cost-of-delay" || tabParam === "sip-vs-lumpsum") {
        setCalculatorTab(tabParam);
      } else {
        setCalculatorTab("direct-vs-regular");
      }
      setIsCalculatorView(true);
      setSelectedArticle(null);
      setIsAdminView(false);
      return;
    }

    if (path.startsWith("/article/")) {
      const slug = path.replace(/^\/article\//, "").replace(/\/+$/, "");
      const matched = currentList.find((p) => p.slug === slug);
      if (matched) {
        setSelectedArticle(matched);
        setIsAdminView(false);
        setIsCalculatorView(false);
        incrementPostViews(matched.id);
        return;
      }
    } else if (path.startsWith("/category/")) {
      const catSlug = path.replace(/^\/category\//, "").replace(/\/+$/, "");
      if (CATEGORY_SLUG_MAP[catSlug]) {
        setCurrentCategory(CATEGORY_SLUG_MAP[catSlug]);
        setSelectedArticle(null);
        setIsAdminView(false);
        setIsCalculatorView(false);
        return;
      }
    } else if (path === "/admin") {
      const session = getCurrentAdminSession();
      if (session) {
        setIsAdminView(true);
        setSelectedArticle(null);
        setIsCalculatorView(false);
      } else {
        setShowAuthModal(true);
      }
      return;
    }

    // Default view
    setSelectedArticle(null);
    setIsAdminView(false);
    setIsCalculatorView(false);
    if (path === "/") {
      setCurrentCategory("all");
    }
  };

  // Open Calculators Suite Page
  const handleOpenCalculators = (tab: "direct-vs-regular" | "step-up" | "cost-of-delay" | "sip-vs-lumpsum" = "direct-vs-regular") => {
    setIsCalculatorView(true);
    setCalculatorTab(tab);
    setSelectedArticle(null);
    setIsAdminView(false);
    const targetUrl = CALCULATOR_CONFIG[tab]?.urlPath || "/calculators";
    window.history.pushState({}, "", targetUrl);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  // Navigate to article (updates URL with pushState for indexable URL)
  const handleOpenArticle = (post: ArticlePost) => {
    setSelectedArticle(post);
    setIsAdminView(false);
    setIsCalculatorView(false);
    incrementPostViews(post.id);
    window.history.pushState({}, "", `/article/${post.slug}`);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  // Switch category with clean indexable URL
  const handleSelectCategory = (cat: ArticleCategory | "all") => {
    setCurrentCategory(cat);
    setSelectedArticle(null);
    setIsAdminView(false);
    setIsCalculatorView(false);
    if (cat === "all") {
      window.history.pushState({}, "", "/");
    } else {
      window.history.pushState({}, "", `/category/${CATEGORY_TO_SLUG[cat]}`);
    }
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  // Back to Blog Home
  const handleBackToHome = () => {
    setSelectedArticle(null);
    setIsAdminView(false);
    setIsCalculatorView(false);
    setShowAuthModal(false);
    setCurrentCategory("all");
    window.history.pushState({}, "", "/");
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleAuthSuccess = (user: AdminUser) => {
    setAdminUser(user);
    setShowAuthModal(false);
    setAdminInitialTab("posts");
    setIsAdminView(true);
    setSelectedArticle(null);
    window.history.pushState({}, "", "/admin");
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleLogout = () => {
    logoutAdmin();
    setAdminUser(null);
    setIsAdminView(false);
    handleBackToHome();
  };

  // Save Post Handler
  const handleSavePost = async (post: ArticlePost) => {
    await savePost(post);
    await loadData();
  };

  // Delete Post Handler
  const handleDeletePost = async (id: string, slug?: string) => {
    if (confirm("Are you sure you want to permanently delete this research article?")) {
      // Optimistic instant UI update
      setPosts((prev) =>
        prev.filter(
          (p) => String(p.id) !== String(id) && (!slug || String(p.slug) !== String(slug))
        )
      );
      await deletePost(id, slug);
      await loadData();
    }
  };

  // Update Settings Handler
  const handleUpdateSettings = (newSettings: SiteSettings) => {
    setSettings(newSettings);
    saveSiteSettings(newSettings);
  };

  // Filter published posts for public view and sort date-wise descending (latest first)
  const publishedPosts = posts
    .filter((p) => p.status === "published")
    .sort((a, b) => {
      const timeA = new Date(a.publishedAt || a.createdAt || 0).getTime();
      const timeB = new Date(b.publishedAt || b.createdAt || 0).getTime();
      return timeB - timeA;
    });

  const filteredPosts = publishedPosts.filter((p) => {
    if (currentCategory !== "all" && p.category !== currentCategory) return false;
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      return (
        p.title.toLowerCase().includes(q) ||
        p.excerpt.toLowerCase().includes(q) ||
        p.category.toLowerCase().includes(q) ||
        p.tags?.some((t) => t.toLowerCase().includes(q)) ||
        p.amfiSchemeCodes?.some((c) => c.includes(q))
      );
    }
    return true;
  });

  return (
    <div className="min-h-screen flex flex-col bg-[#FAF9F5] text-[#1A1A1A] font-serif-editorial">
      {/* SEO & Structured Data Head */}
      <SEOHead
        post={selectedArticle}
        settings={settings}
        calculatorMeta={isCalculatorView ? (CALCULATOR_CONFIG[calculatorTab] || CALCULATOR_CONFIG["direct-vs-regular"]) : null}
        urlPath={
          isCalculatorView
            ? (CALCULATOR_CONFIG[calculatorTab]?.urlPath || "/calculators")
            : selectedArticle
            ? `/article/${selectedArticle.slug}`
            : currentCategory !== "all"
            ? `/category/${CATEGORY_TO_SLUG[currentCategory]}`
            : "/"
        }
        customTitle={
          !isCalculatorView && !selectedArticle && currentCategory !== "all"
            ? `${currentCategory} Mutual Fund Research & Analysis | YieldNest.online`
            : undefined
        }
        customDescription={
          !isCalculatorView && !selectedArticle && currentCategory !== "all"
            ? `Explore data-driven ${currentCategory} mutual fund research, rolling returns, and performance analysis on YieldNest.online.`
            : undefined
        }
      />

      {/* Admin Authentication Login Modal (shown only when visiting /admin without active session) */}
      {showAuthModal && (
        <Suspense fallback={null}>
          <AdminAuthModal
            onSuccess={handleAuthSuccess}
            onCancel={() => {
              setShowAuthModal(false);
              handleBackToHome();
            }}
          />
        </Suspense>
      )}

      {/* Admin View (strictly URL /admin accessible) */}
      {isAdminView && adminUser ? (
        <Suspense fallback={<div className="p-16 text-center text-xs font-mono text-stone-500">Loading research management suite...</div>}>
          <AdminDashboard
            posts={posts}
            comments={comments}
            settings={settings}
            adminUser={adminUser}
            onSavePost={handleSavePost}
            onDeletePost={handleDeletePost}
            onViewPost={handleOpenArticle}
            onCloseAdmin={handleBackToHome}
            onLogoutAdmin={handleLogout}
            onUpdateSettings={handleUpdateSettings}
            initialTab={adminInitialTab}
          />
        </Suspense>
      ) : isCalculatorView ? (
        /* Dedicated Calculators Suite Page */
        <>
          <Navbar
            currentCategory={currentCategory}
            onSelectCategory={(cat) => {
              setIsCalculatorView(false);
              handleSelectCategory(cat);
            }}
            onSearchChange={setSearchQuery}
            searchQuery={searchQuery}
            settings={settings}
            onNavigateHome={handleBackToHome}
            isCalculatorView={true}
            onNavigateCalculators={() => handleOpenCalculators()}
          />

          <main className="flex-1">
            <Suspense fallback={<div className="min-h-screen py-24 text-center text-xs font-mono-data text-stone-500">Loading quantitative calculator suite...</div>}>
              <CalculatorSuitePage
                onBackToHome={handleBackToHome}
                onNavigateArticle={handleOpenArticle}
                allPosts={posts}
                initialTab={calculatorTab}
                onTabChange={(tab) => setCalculatorTab(tab)}
              />
            </Suspense>
          </main>

          <Footer
            settings={settings}
            onSelectCategory={(cat) => {
              setIsCalculatorView(false);
              handleSelectCategory(cat);
            }}
            onNavigateCalculators={() => handleOpenCalculators()}
          />
        </>
      ) : selectedArticle ? (
        /* Single Article View */
        <Suspense fallback={<div className="min-h-screen py-24 text-center text-xs font-mono-data text-stone-500">Loading research report...</div>}>
          <ArticleReader
            post={selectedArticle}
            onBack={handleBackToHome}
            settings={settings}
            onOpenCategory={(cat) => {
              handleSelectCategory(cat);
            }}
            allPosts={posts}
            onNavigateArticle={handleOpenArticle}
          />
        </Suspense>
      ) : (
        /* Blog Main Homepage */
        <>
          <Navbar
            currentCategory={currentCategory}
            onSelectCategory={handleSelectCategory}
            onSearchChange={setSearchQuery}
            searchQuery={searchQuery}
            settings={settings}
            onNavigateHome={handleBackToHome}
            isCalculatorView={false}
            onNavigateCalculators={() => handleOpenCalculators()}
          />

          <main className="flex-1 max-w-6xl w-full mx-auto px-4 py-6 sm:py-8 space-y-10">
            {/* Featured Quantitative Calculators Banner */}
            <div className="bg-gradient-to-r from-[#1e293b] via-[#151f30] to-[#0f172a] text-white p-5 sm:p-6 rounded-2xl border border-slate-700/80 shadow-md flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
              <div className="space-y-1.5">
                <div className="inline-flex items-center gap-1.5 text-[10px] font-mono-data uppercase tracking-wider text-emerald-400 font-semibold px-2.5 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20">
                  <Sparkles className="w-3 h-3 text-emerald-400" />
                  <span>Interactive Quantitative Suite</span>
                </div>
                <h2 className="text-lg sm:text-xl font-bold font-serif-editorial text-white">
                  Mutual Fund Interactive Calculators
                </h2>
                <p className="text-slate-300 text-xs sm:text-sm font-sans max-w-xl">
                  Simulate Direct vs Regular TER drag, step-up SIP compounding, procrastination delay costs, and SIP vs lumpsum entry dynamics.
                </p>
              </div>
              <button
                onClick={() => handleOpenCalculators()}
                className="shrink-0 px-4 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs font-mono-data tracking-wide transition-all shadow-md flex items-center gap-2 group cursor-pointer"
              >
                <span>Launch All 4 Calculators</span>
                <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-0.5 transition-transform" />
              </button>
            </div>

            {/* Loading State */}
            {loading ? (
              <div className="py-20 text-center text-xs font-mono-data text-stone-500">
                Loading research index...
              </div>
            ) : filteredPosts.length === 0 ? (
              /* No Search Results */
              <div className="py-16 text-center bg-white rounded-2xl border border-stone-200 p-8 space-y-3">
                <p className="text-sm font-serif-editorial text-stone-700">
                  No mutual fund reports found matching "{searchQuery}".
                </p>
                <button
                  onClick={() => {
                    setSearchQuery("");
                    setCurrentCategory("all");
                  }}
                  className="text-xs text-stone-900 underline font-medium"
                >
                  Clear all filters
                </button>
              </div>
            ) : (
              /* Articles Listing */
              <div className="space-y-12">
                <section>
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                    {filteredPosts.map((post) => (
                      <ArticleCard
                        key={post.id}
                        post={post}
                        onOpen={handleOpenArticle}
                      />
                    ))}
                  </div>
                </section>

                {/* Newsletter Subscription Block */}
                <NewsletterSignup />
              </div>
            )}
          </main>

          <Footer
            settings={settings}
            onSelectCategory={handleSelectCategory}
            onNavigateCalculators={() => handleOpenCalculators()}
          />
        </>
      )}
    </div>
  );
}
