import React, { useState, useEffect, Suspense, lazy } from "react";
import { Sparkles, ArrowRight, Calculator } from "lucide-react";
import { ArticleCategory, ArticlePost, Comment, SiteSettings, AdminUser } from "./types";
import {
  getAllPosts,
  getInitialPosts,
  savePost,
  deletePost,
  incrementPostViews,
  getAllComments,
  getSiteSettings,
  saveSiteSettings,
  getCurrentAdminSession,
  logoutAdmin,
} from "./lib/storage";
import { SEOHead } from "./components/SEOHead";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { ArticleCard } from "./components/ArticleCard";
import { NewsletterSignup } from "./components/NewsletterSignup";
import { PlaceholderPage, PlaceholderType } from "./components/PlaceholderPage";
import { FAQPage } from "./components/FAQPage";
import { GlossaryPage } from "./components/GlossaryPage";
import { CalculatorsHubPage } from "./components/calculators/CalculatorsHubPage";
import { SipCalculatorPage } from "./components/calculators/SipCalculatorPage";
import { StepUpSipCalculatorPage } from "./components/calculators/StepUpSipCalculatorPage";
import { LumpsumCalculatorPage } from "./components/calculators/LumpsumCalculatorPage";
import { SwpCalculatorPage } from "./components/calculators/SwpCalculatorPage";
import { GoalPlannerCalculatorPage } from "./components/calculators/GoalPlannerCalculatorPage";
import { TaxEstimatorCalculatorPage } from "./components/calculators/TaxEstimatorCalculatorPage";
import { TopicHubPage } from "./components/TopicHubPage";
import { TopicHubsIndexPage } from "./components/TopicHubsIndexPage";
import { TopicHubData, getTopicHubBySlug, TOPIC_HUBS } from "./data/topicHubsData";
import { HowToChooseFundGuide } from "./components/guides/HowToChooseFundGuide";
import { RedemptionChecklistPage } from "./components/guides/RedemptionChecklistPage";
import { GuidesIndexPage } from "./components/guides/GuidesIndexPage";

// Code-split heavy components away from initial public visitor bundle
const ArticleReader = lazy(() =>
  import("./components/ArticleReader").then((m) => ({ default: m.ArticleReader }))
);
const AdminDashboard = lazy(() =>
  import("./components/admin/AdminDashboard").then((m) => ({ default: m.AdminDashboard }))
);
const AdminAuthModal = lazy(() =>
  import("./components/admin/AdminAuthModal").then((m) => ({ default: m.AdminAuthModal }))
);
const CalculatorSuitePage = lazy(() =>
  import("./components/CalculatorSuitePage").then((m) => ({ default: m.CalculatorSuitePage }))
);

const CATEGORY_SLUG_MAP: Record<string, ArticleCategory> = {
  "fund-comparison": "Fund Comparison",
  "performance-analysis": "Performance Analysis",
  "market-trends": "Market Trends",
  "category-deep-dive": "Category Deep-Dive",
  "sip-strategies": "SIP Strategies",
};

const CATEGORY_TO_SLUG: Record<ArticleCategory, string> = {
  "Fund Comparison": "fund-comparison",
  "Performance Analysis": "performance-analysis",
  "Market Trends": "market-trends",
  "Category Deep-Dive": "category-deep-dive",
  "SIP Strategies": "sip-strategies",
};

export const CALCULATOR_CONFIG: Record<
  "direct-vs-regular" | "step-up" | "cost-of-delay" | "sip-vs-lumpsum",
  { name: string; title: string; description: string; urlPath: string }
> = {
  "direct-vs-regular": {
    name: "Direct vs Regular Mutual Fund Calculator",
    title: "Direct vs Regular Fund Calculator | YieldNest",
    description: "Calculate how much wealth you lose to distributor commissions and Total Expense Ratio (TER) drag over your SIP tenure in Indian mutual funds.",
    urlPath: "/calculator/direct-vs-regular",
  },
  "step-up": {
    name: "Step-Up SIP Compounding Calculator",
    title: "Step-Up SIP Compounding Calculator | YieldNest",
    description: "Simulate how increasing your monthly SIP by 5% to 25% each year accelerates your mutual fund corpus. Calculate extra wealth generated by annual step-ups.",
    urlPath: "/calculator/step-up-sip",
  },
  "cost-of-delay": {
    name: "Cost of Delay SIP Calculator",
    title: "Cost of Delay SIP Calculator | YieldNest",
    description: "Find out how much money you lose by delaying your mutual fund SIP by 6 months, 1 year, or 2 years. Calculate the compound interest penalty of waiting.",
    urlPath: "/calculator/cost-of-delay",
  },
  "sip-vs-lumpsum": {
    name: "SIP vs Lumpsum Mutual Fund Strategy Comparator",
    title: "SIP vs Lumpsum Calculator | YieldNest",
    description: "Compare mutual fund returns between a one-time lumpsum investment and a staggered monthly SIP over the same time horizon with delta analysis.",
    urlPath: "/calculator/sip-vs-lumpsum",
  },
};

export const PLACEHOLDER_SEO: Record<
  PlaceholderType,
  { title: string; description: string; urlPath: string; keywords: string }
> = {
  faq: {
    title: "Frequently Asked Questions (FAQ) | YieldNest",
    description: "Answers to common retail investor questions about mutual fund safety, capital gains tax, SIP compounding, and redemption in India.",
    urlPath: "/faq",
    keywords: "mutual fund FAQ, is mutual fund safe, mutual fund tax rules, SIP questions, mutual fund redemption time",
  },
  glossary: {
    title: "Mutual Fund Glossary: Key Terms & Definitions | YieldNest",
    description: "A comprehensive glossary of essential Indian mutual fund terms including NAV, TER, ISIN, CAN, IDCW, exit loads, and SEBI regulations.",
    urlPath: "/glossary",
    keywords: "mutual fund glossary, NAV meaning, TER meaning, ISIN mutual fund, CAN mutual fund, IDCW meaning, exit load",
  },
  guides: {
    title: "Mutual Fund Investor Guides & Educational Pillars | YieldNest",
    description: "In-depth educational guides covering mutual fund fundamentals, portfolio building, risk evaluation, and asset allocation for Indian investors.",
    urlPath: "/guides",
    keywords: "mutual fund guide, how to invest in mutual funds, mutual fund basics, asset allocation India, direct mutual funds",
  },
  calculators: {
    title: "Quantitative Mutual Fund Calculators Suite | YieldNest",
    description: "Interactive calculators for Indian mutual funds: Direct vs Regular TER drag, step-up SIP compounding, cost of delay, and SIP vs lumpsum.",
    urlPath: "/calculators",
    keywords: "mutual fund calculator, direct vs regular calculator, step up sip calculator, cost of delay calculator, sip vs lumpsum calculator",
  },
};

export type CalculatorPageViewType = "hub" | "sip" | "step-up-sip" | "lumpsum" | "swp" | "goal-planner" | "tax-estimator" | "direct-vs-regular" | "cost-of-delay" | "sip-vs-lumpsum";

export type GuidePageViewType = "index" | "how-to-choose" | "redemption";

export const DEDICATED_GUIDE_SEO: Record<
  "how-to-choose" | "redemption",
  { title: string; description: string; urlPath: string; keywords: string }
> = {
  "how-to-choose": {
    title: "How to Choose a Mutual Fund: 10-Point Checklist & Category Quiz | YieldNest",
    description: "Interactive pre-investment checklist and goal/risk-profile evaluation quiz mapping your horizon to SEBI fund categories with structural rationale and risks.",
    urlPath: "/guides/how-to-choose-a-mutual-fund",
    keywords: "how to choose a mutual fund, mutual fund checklist, fund category quiz, SEBI mutual fund categories, mutual fund due diligence",
  },
  redemption: {
    title: "Printable Mutual Fund Redemption Checklist | YieldNest",
    description: "A printable 12-step pre-redemption verification audit covering exit loads, ELSS 3-year lock-ins, Section 112A capital gains tax, and SEBI cut-off times.",
    urlPath: "/guides/redemption-checklist",
    keywords: "mutual fund redemption checklist, printable mutual fund checklist, exit load mutual funds, ELSS lock in rules, capital gains tax redemption",
  },
};

export const INDIVIDUAL_CALCULATOR_SEO: Record<
  string,
  { name: string; title: string; description: string; urlPath: string; keywords: string }
> = {
  hub: {
    name: "Quantitative Mutual Fund Calculators Suite",
    title: "Quantitative Mutual Fund Calculators Suite | YieldNest",
    description: "Comprehensive suite of quantitative Indian mutual fund calculators including SIP, Step-Up SIP, Lumpsum, SWP, Goal Planner, Direct vs Regular TER drag, and Tax Estimator.",
    urlPath: "/calculators",
    keywords: "mutual fund calculator, SIP calculator, lumpsum calculator, step up sip calculator, direct vs regular calculator",
  },
  sip: {
    name: "SIP Compounding Calculator",
    title: "SIP Calculator: Mutual Fund Wealth Compounding | YieldNest",
    description: "Calculate future maturity value of your monthly Systematic Investment Plan (SIP) in Indian mutual funds with compounding growth chart and amortization schedule.",
    urlPath: "/calculators/sip",
    keywords: "SIP calculator, mutual fund SIP calculator, monthly SIP compounding, SIP maturity value India, mutual fund tax SIP",
  },
  "step-up-sip": {
    name: "Step-Up SIP Compounding Calculator",
    title: "Step-Up SIP Calculator: Annual Top-Up Compounding | YieldNest",
    description: "Simulate how annual step-up top-ups (5% to 25%) linked to salary appraisals accelerate mutual fund wealth creation compared to static SIPs.",
    urlPath: "/calculators/step-up-sip",
    keywords: "step up SIP calculator, top up SIP calculator, annual step up mutual fund, step up compounding, salary increment SIP",
  },
  lumpsum: {
    name: "Lumpsum Investment Calculator",
    title: "Lumpsum Calculator: One-Time Mutual Fund Compounding | YieldNest",
    description: "Calculate multi-year compounded returns and capital gains tax on one-time lumpsum mutual fund investments in India.",
    urlPath: "/calculators/lumpsum",
    keywords: "lumpsum calculator, one time mutual fund investment, lumpsum compounding India, mutual fund lumpsum returns",
  },
  swp: {
    name: "Systematic Withdrawal Plan (SWP) Calculator",
    title: "SWP Calculator: Systematic Withdrawal Plan & Longevity | YieldNest",
    description: "Simulate systematic monthly withdrawals from your mutual fund corpus. Calculate total withdrawals, final balance, and portfolio depletion horizon with monthly compounding.",
    urlPath: "/calculators/swp",
    keywords: "SWP calculator, systematic withdrawal plan calculator, mutual fund SWP, retirement monthly withdrawal, SWP corpus longevity",
  },
  "goal-planner": {
    name: "Mutual Fund Goal Planner Calculator",
    title: "Goal Planner Calculator: Inflation-Adjusted Target & Required SIP | YieldNest",
    description: "Calculate inflation-adjusted future target cost and the required monthly mutual fund SIP to achieve life goals like child education, home purchase, and retirement.",
    urlPath: "/calculators/goal-planner",
    keywords: "goal planner calculator, inflation adjusted goal calculator, mutual fund goal planning, target SIP calculator, child education SIP calculator",
  },
  "tax-estimator": {
    name: "Mutual Fund Capital Gains Tax Estimator",
    title: "Mutual Fund Tax Estimator: Capital Gains & Net Proceeds | YieldNest",
    description: "Calculate capital gains tax, holding period classification, Section 112A exemption, and net realization proceeds on mutual fund redemptions in India under Finance Act 2024.",
    urlPath: "/calculators/tax-estimator",
    keywords: "mutual fund tax calculator, capital gains tax mutual funds, equity LTCG calculator, debt fund taxation, Section 112A calculator",
  },
  "direct-vs-regular": {
    name: "Direct vs Regular Mutual Fund Calculator",
    title: "Direct vs Regular Fund Calculator | YieldNest",
    description: "Calculate how much wealth you lose to distributor commissions and Total Expense Ratio (TER) drag over your SIP tenure in Indian mutual funds.",
    urlPath: "/calculators/direct-vs-regular",
    keywords: "direct vs regular mutual fund, TER drag calculator, mutual fund commission loss, direct fund compounding",
  },
  "cost-of-delay": {
    name: "Cost of Delay SIP Calculator",
    title: "Cost of Delay SIP Calculator | YieldNest",
    description: "Find out how much money you lose by delaying your mutual fund SIP by 6 months, 1 year, or 2 years. Calculate the compound interest penalty of waiting.",
    urlPath: "/calculators/cost-of-delay",
    keywords: "cost of delay calculator, delay SIP penalty, mutual fund procrastination cost, compounding delay loss",
  },
  "sip-vs-lumpsum": {
    name: "SIP vs Lumpsum Strategy Comparator",
    title: "SIP vs Lumpsum Calculator | YieldNest",
    description: "Compare mutual fund returns between a one-time lumpsum investment and a staggered monthly SIP over the same time horizon with delta analysis.",
    urlPath: "/calculators/sip-vs-lumpsum",
    keywords: "SIP vs lumpsum calculator, lump sum vs SIP comparison, mutual fund investing strategy comparator",
  },
};

export default function App() {
  const [posts, setPosts] = useState<ArticlePost[]>(() => getInitialPosts());
  const [comments, setComments] = useState<Comment[]>([]);
  const [settings, setSettings] = useState<SiteSettings>(getSiteSettings());
  const [currentCategory, setCurrentCategory] = useState<ArticleCategory | "all">("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedArticle, setSelectedArticle] = useState<ArticlePost | null>(null);
  const [isAdminView, setIsAdminView] = useState(false);
  const [adminInitialTab, setAdminInitialTab] = useState<string>("posts");
  const [adminUser, setAdminUser] = useState<AdminUser | null>(getCurrentAdminSession());
  const [showAuthModal, setShowAuthModal] = useState(false);
  const [loading, setLoading] = useState(false);
  const [isCalculatorView, setIsCalculatorView] = useState(false);
  const [activeCalculatorPage, setActiveCalculatorPage] = useState<CalculatorPageViewType>("hub");
  const [calculatorTab, setCalculatorTab] = useState<"direct-vs-regular" | "step-up" | "cost-of-delay" | "sip-vs-lumpsum">("direct-vs-regular");
  const [placeholderView, setPlaceholderView] = useState<PlaceholderType | null>(null);
  const [activeGuidePage, setActiveGuidePage] = useState<GuidePageViewType>("index");
  const [selectedHub, setSelectedHub] = useState<TopicHubData | null>(null);
  const [isHubsIndexView, setIsHubsIndexView] = useState(false);

  // Initialize and handle URL routing (Instant zero-delay resolution from preloaded state)
  useEffect(() => {
    // Resolve initial route immediately using synchronous baseline (0ms blocking)
    handleRouteFromUrl(posts);

    // Defer background data refresh to idle time to guarantee fast FCP/LCP
    const runBackgroundSync = () => {
      loadData();
    };

    if ("requestIdleCallback" in window) {
      (window as any).requestIdleCallback(runBackgroundSync, { timeout: 2000 });
    } else {
      setTimeout(runBackgroundSync, 600);
    }

    const handlePopState = () => {
      handleRouteFromUrl();
    };
    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, []);

  const loadData = async () => {
    try {
      const loadedPosts = await getAllPosts();
      const loadedComments = await getAllComments();
      const loadedSettings = getSiteSettings();
      setPosts(loadedPosts);
      setComments(loadedComments);
      setSettings(loadedSettings);
      setAdminUser(getCurrentAdminSession());
      // Re-check route with freshly loaded posts in case of deep direct link
      handleRouteFromUrl(loadedPosts);
    } catch (err) {
      console.warn("Background posts sync notice:", err);
    }
  };

  const handleRouteFromUrl = (availablePosts?: ArticlePost[]) => {
    const rawPath = window.location.pathname;
    const path = rawPath.replace(/\/+$/, "") || "/";
    const currentList = availablePosts && availablePosts.length > 0 ? availablePosts : posts;

    // Topic Hubs Index or Specific Topic Hub
    if (path === "/hubs" || path === "/topics") {
      setIsHubsIndexView(true);
      setSelectedHub(null);
      setIsCalculatorView(false);
      setSelectedArticle(null);
      setIsAdminView(false);
      setPlaceholderView(null);
      return;
    } else if (path.startsWith("/hub/") || path.startsWith("/topic/") || path.startsWith("/topics/")) {
      const hubSlug = path.replace(/^\/(hub|topic|topics)\//, "").replace(/\/+$/, "");
      const matchedHub = getTopicHubBySlug(hubSlug);
      if (matchedHub) {
        setSelectedHub(matchedHub);
        setIsHubsIndexView(false);
        setIsCalculatorView(false);
        setSelectedArticle(null);
        setIsAdminView(false);
        setPlaceholderView(null);
        return;
      }
    }

    // Check for individual calculator dedicated URLs & calculators hub
    if (path === "/faq") {
      setPlaceholderView("faq");
      setIsCalculatorView(false);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (path === "/glossary") {
      setPlaceholderView("glossary");
      setIsCalculatorView(false);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (path === "/guides/how-to-choose-a-mutual-fund" || path === "/how-to-choose-a-mutual-fund") {
      setPlaceholderView("guides");
      setActiveGuidePage("how-to-choose");
      setIsCalculatorView(false);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (path === "/guides/redemption-checklist" || path === "/redemption-checklist") {
      setPlaceholderView("guides");
      setActiveGuidePage("redemption");
      setIsCalculatorView(false);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (path === "/guides" || path === "/guide") {
      setPlaceholderView("guides");
      setActiveGuidePage("index");
      setIsCalculatorView(false);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (path === "/calculators/sip" || path === "/calculator/sip") {
      setIsCalculatorView(true);
      setActiveCalculatorPage("sip");
      setPlaceholderView(null);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (
      path === "/calculators/step-up-sip" ||
      path === "/calculator/step-up-sip" ||
      path === "/calculator/step-up" ||
      path === "/calculators/step-up" ||
      path === "/calculator/stepup" ||
      path === "/calculators/stepup"
    ) {
      setIsCalculatorView(true);
      setActiveCalculatorPage("step-up-sip");
      setCalculatorTab("step-up");
      setPlaceholderView(null);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (path === "/calculators/lumpsum" || path === "/calculator/lumpsum" || path === "/calculators/lump-sum" || path === "/calculator/lump-sum") {
      setIsCalculatorView(true);
      setActiveCalculatorPage("lumpsum");
      setPlaceholderView(null);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (path === "/calculators/swp" || path === "/calculator/swp") {
      setIsCalculatorView(true);
      setActiveCalculatorPage("swp");
      setPlaceholderView(null);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (
      path === "/calculators/goal-planner" ||
      path === "/calculator/goal-planner" ||
      path === "/calculators/goal" ||
      path === "/calculator/goal" ||
      path === "/calculators/goalplanner" ||
      path === "/calculator/goalplanner"
    ) {
      setIsCalculatorView(true);
      setActiveCalculatorPage("goal-planner");
      setPlaceholderView(null);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (
      path === "/calculators/tax-estimator" ||
      path === "/calculator/tax-estimator" ||
      path === "/calculators/tax" ||
      path === "/calculator/tax" ||
      path === "/calculators/taxestimator" ||
      path === "/calculator/taxestimator"
    ) {
      setIsCalculatorView(true);
      setActiveCalculatorPage("tax-estimator");
      setPlaceholderView(null);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (
      path === "/calculator/direct-vs-regular" ||
      path === "/calculators/direct-vs-regular" ||
      path === "/calculators/ter" ||
      path === "/calculator/ter"
    ) {
      setCalculatorTab("direct-vs-regular");
      setActiveCalculatorPage("direct-vs-regular");
      setIsCalculatorView(true);
      setPlaceholderView(null);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (path === "/calculator/cost-of-delay" || path === "/calculators/cost-of-delay" || path === "/calculators/delay" || path === "/calculator/delay") {
      setCalculatorTab("cost-of-delay");
      setActiveCalculatorPage("cost-of-delay");
      setIsCalculatorView(true);
      setPlaceholderView(null);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (
      path === "/calculator/sip-vs-lumpsum" ||
      path === "/calculators/sip-vs-lumpsum" ||
      path === "/calculators/comparator" ||
      path === "/calculator/comparator"
    ) {
      setCalculatorTab("sip-vs-lumpsum");
      setActiveCalculatorPage("sip-vs-lumpsum");
      setIsCalculatorView(true);
      setPlaceholderView(null);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (
      path === "/calculators" ||
      path === "/calculator" ||
      path === "/calculator-suite" ||
      path === "/calculators-suite"
    ) {
      const searchParams = new URLSearchParams(window.location.search);
      const tabParam = (
        searchParams.get("tab") ||
        searchParams.get("calc") ||
        searchParams.get("calculator") ||
        searchParams.get("tool") ||
        searchParams.get("type") ||
        searchParams.get("view") ||
        ""
      ).toLowerCase();

      if (tabParam === "sip") {
        setActiveCalculatorPage("sip");
      } else if (tabParam === "step-up" || tabParam === "step-up-sip" || tabParam === "stepup") {
        setActiveCalculatorPage("step-up-sip");
        setCalculatorTab("step-up");
      } else if (tabParam === "lumpsum" || tabParam === "lump-sum") {
        setActiveCalculatorPage("lumpsum");
      } else if (tabParam === "swp") {
        setActiveCalculatorPage("swp");
      } else if (tabParam === "goal-planner" || tabParam === "goal" || tabParam === "goalplanner") {
        setActiveCalculatorPage("goal-planner");
      } else if (tabParam === "tax-estimator" || tabParam === "tax" || tabParam === "taxestimator") {
        setActiveCalculatorPage("tax-estimator");
      } else if (tabParam === "cost-of-delay" || tabParam === "delay") {
        setActiveCalculatorPage("cost-of-delay");
        setCalculatorTab("cost-of-delay");
      } else if (tabParam === "sip-vs-lumpsum" || tabParam === "comparator" || tabParam === "compare") {
        setActiveCalculatorPage("sip-vs-lumpsum");
        setCalculatorTab("sip-vs-lumpsum");
      } else if (tabParam === "direct-vs-regular" || tabParam === "ter" || tabParam === "regular-vs-direct") {
        setActiveCalculatorPage("direct-vs-regular");
        setCalculatorTab("direct-vs-regular");
      } else {
        setActiveCalculatorPage("hub");
      }
      setIsCalculatorView(true);
      setPlaceholderView(null);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    } else if (path.startsWith("/calculators/") || path.startsWith("/calculator/")) {
      const sub = path.replace(/^\/(calculators|calculator)\//, "").toLowerCase();
      if (sub === "sip") {
        setActiveCalculatorPage("sip");
      } else if (sub === "step-up-sip" || sub === "step-up" || sub === "stepup") {
        setActiveCalculatorPage("step-up-sip");
        setCalculatorTab("step-up");
      } else if (sub === "lumpsum" || sub === "lump-sum") {
        setActiveCalculatorPage("lumpsum");
      } else if (sub === "swp") {
        setActiveCalculatorPage("swp");
      } else if (sub === "goal-planner" || sub === "goal" || sub === "goalplanner") {
        setActiveCalculatorPage("goal-planner");
      } else if (sub === "tax-estimator" || sub === "tax" || sub === "taxestimator") {
        setActiveCalculatorPage("tax-estimator");
      } else if (sub === "direct-vs-regular" || sub === "ter") {
        setActiveCalculatorPage("direct-vs-regular");
        setCalculatorTab("direct-vs-regular");
      } else if (sub === "cost-of-delay" || sub === "delay") {
        setActiveCalculatorPage("cost-of-delay");
        setCalculatorTab("cost-of-delay");
      } else if (sub === "sip-vs-lumpsum" || sub === "compare" || sub === "comparator") {
        setActiveCalculatorPage("sip-vs-lumpsum");
        setCalculatorTab("sip-vs-lumpsum");
      } else {
        setActiveCalculatorPage("hub");
      }
      setIsCalculatorView(true);
      setPlaceholderView(null);
      setSelectedArticle(null);
      setIsAdminView(false);
      setSelectedHub(null);
      setIsHubsIndexView(false);
      return;
    }

    if (path.startsWith("/article/")) {
      const slug = path.replace(/^\/article\//, "").replace(/\/+$/, "");
      const matched = currentList.find((p) => p.slug === slug);
      if (matched) {
        setSelectedArticle(matched);
        setIsAdminView(false);
        setIsCalculatorView(false);
        setPlaceholderView(null);
        setSelectedHub(null);
        setIsHubsIndexView(false);
        incrementPostViews(matched.id);
        return;
      }
    } else if (path.startsWith("/category/")) {
      const catSlug = path.replace(/^\/category\//, "").replace(/\/+$/, "");
      if (CATEGORY_SLUG_MAP[catSlug]) {
        setCurrentCategory(CATEGORY_SLUG_MAP[catSlug]);
        setSelectedArticle(null);
        setIsAdminView(false);
        setIsCalculatorView(false);
        setPlaceholderView(null);
        setSelectedHub(null);
        setIsHubsIndexView(false);
        return;
      }
    } else if (path === "/admin") {
      const session = getCurrentAdminSession();
      if (session) {
        setIsAdminView(true);
        setSelectedArticle(null);
        setIsCalculatorView(false);
        setPlaceholderView(null);
        setSelectedHub(null);
        setIsHubsIndexView(false);
      } else {
        setShowAuthModal(true);
      }
      return;
    }

    // Default view
    setSelectedArticle(null);
    setIsAdminView(false);
    setIsCalculatorView(false);
    setPlaceholderView(null);
    setSelectedHub(null);
    setIsHubsIndexView(false);
    if (path === "/") {
      setCurrentCategory("all");
    }
  };

  // Open Calculators Suite Page or individual calculator
  const handleOpenCalculators = (target?: string) => {
    setIsCalculatorView(true);
    setPlaceholderView(null);
    setSelectedArticle(null);
    setIsAdminView(false);
    setSelectedHub(null);
    setIsHubsIndexView(false);

    const queryString = target && target.includes("?") ? `?${target.split("?")[1]}` : "";
    const cleanTarget = target
      ? target
          .split("?")[0]
          .replace(/^\/+(calculators|calculator|calculator-suite)?\//, "")
          .replace(/^\//, "")
          .toLowerCase()
      : "";

    if (cleanTarget === "sip") {
      setActiveCalculatorPage("sip");
      window.history.pushState({}, "", `/calculators/sip${queryString}`);
    } else if (cleanTarget === "step-up-sip" || cleanTarget === "step-up" || cleanTarget === "stepup") {
      setActiveCalculatorPage("step-up-sip");
      setCalculatorTab("step-up");
      window.history.pushState({}, "", `/calculators/step-up-sip${queryString}`);
    } else if (cleanTarget === "lumpsum" || cleanTarget === "lump-sum") {
      setActiveCalculatorPage("lumpsum");
      window.history.pushState({}, "", `/calculators/lumpsum${queryString}`);
    } else if (cleanTarget === "swp") {
      setActiveCalculatorPage("swp");
      window.history.pushState({}, "", `/calculators/swp${queryString}`);
    } else if (cleanTarget === "goal-planner" || cleanTarget === "goal" || cleanTarget === "goalplanner") {
      setActiveCalculatorPage("goal-planner");
      window.history.pushState({}, "", `/calculators/goal-planner${queryString}`);
    } else if (cleanTarget === "tax-estimator" || cleanTarget === "tax" || cleanTarget === "taxestimator") {
      setActiveCalculatorPage("tax-estimator");
      window.history.pushState({}, "", `/calculators/tax-estimator${queryString}`);
    } else if (cleanTarget === "direct-vs-regular" || cleanTarget === "ter") {
      setActiveCalculatorPage("direct-vs-regular");
      setCalculatorTab("direct-vs-regular");
      window.history.pushState({}, "", `/calculators/direct-vs-regular${queryString}`);
    } else if (cleanTarget === "cost-of-delay" || cleanTarget === "delay") {
      setActiveCalculatorPage("cost-of-delay");
      setCalculatorTab("cost-of-delay");
      window.history.pushState({}, "", `/calculators/cost-of-delay${queryString}`);
    } else if (cleanTarget === "sip-vs-lumpsum" || cleanTarget === "compare" || cleanTarget === "comparator") {
      setActiveCalculatorPage("sip-vs-lumpsum");
      setCalculatorTab("sip-vs-lumpsum");
      window.history.pushState({}, "", `/calculators/sip-vs-lumpsum${queryString}`);
    } else {
      setActiveCalculatorPage("hub");
      window.history.pushState({}, "", `/calculators${queryString}`);
    }
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  // Navigate to Topic Hub or Hubs Directory
  const handleNavigateHub = (hubSlug?: string) => {
    setSelectedArticle(null);
    setIsAdminView(false);
    setIsCalculatorView(false);
    setPlaceholderView(null);

    if (!hubSlug || hubSlug === "all" || hubSlug === "") {
      setIsHubsIndexView(true);
      setSelectedHub(null);
      window.history.pushState({}, "", "/hubs");
      window.scrollTo({ top: 0, behavior: "smooth" });
      return;
    }

    const matched = getTopicHubBySlug(hubSlug);
    if (matched) {
      setSelectedHub(matched);
      setIsHubsIndexView(false);
      window.history.pushState({}, "", `/hub/${matched.slug}`);
      window.scrollTo({ top: 0, behavior: "smooth" });
    }
  };

  // Navigate to FAQ Page
  const handleNavigateFAQ = () => {
    setPlaceholderView("faq");
    setIsCalculatorView(false);
    setSelectedArticle(null);
    setIsAdminView(false);
    setSelectedHub(null);
    setIsHubsIndexView(false);
    window.history.pushState({}, "", "/faq");
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  // Navigate to Glossary Page
  const handleNavigateGlossary = () => {
    setPlaceholderView("glossary");
    setIsCalculatorView(false);
    setSelectedArticle(null);
    setIsAdminView(false);
    setSelectedHub(null);
    setIsHubsIndexView(false);
    window.history.pushState({}, "", "/glossary");
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  // Navigate to Guides Page or specific Guide
  const handleNavigateGuides = (subguide?: GuidePageViewType) => {
    setPlaceholderView("guides");
    setActiveGuidePage(subguide || "index");
    setIsCalculatorView(false);
    setSelectedArticle(null);
    setIsAdminView(false);
    setSelectedHub(null);
    setIsHubsIndexView(false);
    if (subguide === "how-to-choose") {
      window.history.pushState({}, "", "/guides/how-to-choose-a-mutual-fund");
    } else if (subguide === "redemption") {
      window.history.pushState({}, "", "/guides/redemption-checklist");
    } else {
      window.history.pushState({}, "", "/guides");
    }
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  // Navigate to article (updates URL with pushState for indexable URL)
  const handleOpenArticle = (post: ArticlePost) => {
    setSelectedArticle(post);
    setIsAdminView(false);
    setIsCalculatorView(false);
    setPlaceholderView(null);
    setSelectedHub(null);
    setIsHubsIndexView(false);
    incrementPostViews(post.id);
    window.history.pushState({}, "", `/article/${post.slug}`);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  // Switch category with clean indexable URL
  const handleSelectCategory = (cat: ArticleCategory | "all") => {
    setCurrentCategory(cat);
    setSelectedArticle(null);
    setIsAdminView(false);
    setIsCalculatorView(false);
    setPlaceholderView(null);
    setSelectedHub(null);
    setIsHubsIndexView(false);
    if (cat === "all") {
      window.history.pushState({}, "", "/");
    } else {
      window.history.pushState({}, "", `/category/${CATEGORY_TO_SLUG[cat]}`);
    }
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  // Back to Blog Home
  const handleBackToHome = () => {
    setSelectedArticle(null);
    setIsAdminView(false);
    setIsCalculatorView(false);
    setShowAuthModal(false);
    setSelectedHub(null);
    setIsHubsIndexView(false);
    setPlaceholderView(null);
    setCurrentCategory("all");
    window.history.pushState({}, "", "/");
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleAuthSuccess = (user: AdminUser) => {
    setAdminUser(user);
    setShowAuthModal(false);
    setAdminInitialTab("posts");
    setIsAdminView(true);
    setSelectedArticle(null);
    window.history.pushState({}, "", "/admin");
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleLogout = () => {
    logoutAdmin();
    setAdminUser(null);
    setIsAdminView(false);
    handleBackToHome();
  };

  // Save Post Handler
  const handleSavePost = async (post: ArticlePost) => {
    await savePost(post);
    await loadData();
  };

  // Delete Post Handler
  const handleDeletePost = async (id: string, slug?: string) => {
    if (confirm("Are you sure you want to permanently delete this research article?")) {
      // Optimistic instant UI update
      setPosts((prev) =>
        prev.filter(
          (p) => String(p.id) !== String(id) && (!slug || String(p.slug) !== String(slug))
        )
      );
      await deletePost(id, slug);
      await loadData();
    }
  };

  // Update Settings Handler
  const handleUpdateSettings = (newSettings: SiteSettings) => {
    setSettings(newSettings);
    saveSiteSettings(newSettings);
  };

  // Filter published posts for public view and sort date-wise descending (latest first)
  const publishedPosts = posts
    .filter((p) => p.status === "published")
    .sort((a, b) => {
      const timeA = new Date(a.publishedAt || a.createdAt || 0).getTime();
      const timeB = new Date(b.publishedAt || b.createdAt || 0).getTime();
      return timeB - timeA;
    });

  const filteredPosts = publishedPosts.filter((p) => {
    if (currentCategory !== "all" && p.category !== currentCategory) return false;
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      return (
        p.title.toLowerCase().includes(q) ||
        p.excerpt.toLowerCase().includes(q) ||
        p.category.toLowerCase().includes(q) ||
        p.tags?.some((t) => t.toLowerCase().includes(q)) ||
        p.amfiSchemeCodes?.some((c) => c.includes(q))
      );
    }
    return true;
  });

  return (
    <div className="min-h-screen flex flex-col bg-[#FAF9F5] text-[#1A1A1A] font-serif-editorial">
      {/* SEO & Structured Data Head */}
      <SEOHead
        post={selectedArticle}
        settings={settings}
        calculatorMeta={
          isCalculatorView
            ? {
                name:
                  INDIVIDUAL_CALCULATOR_SEO[activeCalculatorPage]?.name ||
                  CALCULATOR_CONFIG[calculatorTab]?.name ||
                  "Quantitative Mutual Fund Calculators Suite",
                title:
                  INDIVIDUAL_CALCULATOR_SEO[activeCalculatorPage]?.title ||
                  CALCULATOR_CONFIG[calculatorTab]?.title ||
                  "Quantitative Mutual Fund Calculators Suite | YieldNest",
                description:
                  INDIVIDUAL_CALCULATOR_SEO[activeCalculatorPage]?.description ||
                  CALCULATOR_CONFIG[calculatorTab]?.description ||
                  "Comprehensive suite of quantitative Indian mutual fund calculators.",
                urlPath:
                  INDIVIDUAL_CALCULATOR_SEO[activeCalculatorPage]?.urlPath ||
                  CALCULATOR_CONFIG[calculatorTab]?.urlPath ||
                  "/calculators",
              }
            : null
        }
        urlPath={
          selectedHub
            ? `/hub/${selectedHub.slug}`
            : isHubsIndexView
            ? "/hubs"
            : placeholderView === "guides" && (activeGuidePage === "how-to-choose" || activeGuidePage === "redemption")
            ? DEDICATED_GUIDE_SEO[activeGuidePage].urlPath
            : placeholderView
            ? PLACEHOLDER_SEO[placeholderView].urlPath
            : isCalculatorView
            ? (INDIVIDUAL_CALCULATOR_SEO[activeCalculatorPage]?.urlPath || CALCULATOR_CONFIG[calculatorTab]?.urlPath || "/calculators")
            : selectedArticle
            ? `/article/${selectedArticle.slug}`
            : currentCategory !== "all"
            ? `/category/${CATEGORY_TO_SLUG[currentCategory]}`
            : "/"
        }
        customTitle={
          selectedHub
            ? selectedHub.metaTitle
            : isHubsIndexView
            ? "Mutual Fund Topic Hubs: Systematic Knowledge Clusters | YieldNest"
            : placeholderView === "guides" && (activeGuidePage === "how-to-choose" || activeGuidePage === "redemption")
            ? DEDICATED_GUIDE_SEO[activeGuidePage].title
            : placeholderView
            ? PLACEHOLDER_SEO[placeholderView].title
            : isCalculatorView && INDIVIDUAL_CALCULATOR_SEO[activeCalculatorPage]
            ? INDIVIDUAL_CALCULATOR_SEO[activeCalculatorPage].title
            : !isCalculatorView && !selectedArticle && currentCategory !== "all"
            ? `${currentCategory} Mutual Fund Research & Analysis | YieldNest.online`
            : undefined
        }
        customDescription={
          selectedHub
            ? selectedHub.metaDescription
            : isHubsIndexView
            ? "Explore our comprehensive editorial knowledge hubs organized by core investment clusters: Basics, Safety & Risk, Tax & ELSS, Fees, Redemption, SIP, and Comparisons."
            : placeholderView === "guides" && (activeGuidePage === "how-to-choose" || activeGuidePage === "redemption")
            ? DEDICATED_GUIDE_SEO[activeGuidePage].description
            : placeholderView
            ? PLACEHOLDER_SEO[placeholderView].description
            : isCalculatorView && INDIVIDUAL_CALCULATOR_SEO[activeCalculatorPage]
            ? INDIVIDUAL_CALCULATOR_SEO[activeCalculatorPage].description
            : !isCalculatorView && !selectedArticle && currentCategory !== "all"
            ? `Explore data-driven ${currentCategory} mutual fund research, rolling returns, and performance analysis on YieldNest.online.`
            : undefined
        }
        customKeywords={
          selectedHub
            ? selectedHub.keywords
            : isHubsIndexView
            ? "mutual fund topics, mutual fund clusters, SEBI investment guide, AMFI topic hubs, mutual fund basics"
            : placeholderView === "guides" && (activeGuidePage === "how-to-choose" || activeGuidePage === "redemption")
            ? DEDICATED_GUIDE_SEO[activeGuidePage].keywords
            : placeholderView
            ? PLACEHOLDER_SEO[placeholderView].keywords
            : isCalculatorView && INDIVIDUAL_CALCULATOR_SEO[activeCalculatorPage]
            ? INDIVIDUAL_CALCULATOR_SEO[activeCalculatorPage].keywords
            : undefined
        }
      />

      {/* Admin Authentication Login Modal (shown only when visiting /admin without active session) */}
      {showAuthModal && (
        <Suspense fallback={null}>
          <AdminAuthModal
            onSuccess={handleAuthSuccess}
            onCancel={() => {
              setShowAuthModal(false);
              handleBackToHome();
            }}
          />
        </Suspense>
      )}

      {/* Admin View (strictly URL /admin accessible) */}
      {isAdminView && adminUser ? (
        <Suspense fallback={<div className="p-16 text-center text-xs font-mono text-stone-500">Loading research management suite...</div>}>
          <AdminDashboard
            posts={posts}
            comments={comments}
            settings={settings}
            adminUser={adminUser}
            onSavePost={handleSavePost}
            onDeletePost={handleDeletePost}
            onViewPost={handleOpenArticle}
            onCloseAdmin={handleBackToHome}
            onLogoutAdmin={handleLogout}
            onUpdateSettings={handleUpdateSettings}
            initialTab={adminInitialTab}
          />
        </Suspense>
      ) : selectedHub ? (
        /* Reusable Topic Hub Page for Selected Cluster */
        <TopicHubPage
          hub={selectedHub}
          settings={settings}
          allPosts={posts}
          onNavigateHome={handleBackToHome}
          onNavigateCalculators={() => handleOpenCalculators()}
          onNavigateCalculator={(url) => handleOpenCalculators(url)}
          onNavigateFAQ={handleNavigateFAQ}
          onNavigateGlossary={handleNavigateGlossary}
          onNavigateGlossaryTerm={(termId) => {
            handleNavigateGlossary();
            setTimeout(() => {
              const el = document.getElementById(termId);
              if (el) el.scrollIntoView({ behavior: "smooth", block: "center" });
            }, 250);
          }}
          onNavigateGuides={handleNavigateGuides}
          onNavigateHub={handleNavigateHub}
          onSelectCategory={(cat) => {
            setSelectedHub(null);
            handleSelectCategory(cat);
          }}
          onNavigateArticle={handleOpenArticle}
          onSearchChange={setSearchQuery}
          searchQuery={searchQuery}
        />
      ) : isHubsIndexView ? (
        /* Topic Hubs Directory / Index */
        <TopicHubsIndexPage
          settings={settings}
          allPosts={posts}
          onNavigateHome={handleBackToHome}
          onNavigateHub={handleNavigateHub}
          onNavigateCalculators={() => handleOpenCalculators()}
          onNavigateFAQ={handleNavigateFAQ}
          onNavigateGlossary={handleNavigateGlossary}
          onNavigateGuides={handleNavigateGuides}
          onSelectCategory={(cat) => {
            setIsHubsIndexView(false);
            handleSelectCategory(cat);
          }}
          onSearchChange={setSearchQuery}
          searchQuery={searchQuery}
        />
      ) : placeholderView ? (
        placeholderView === "faq" ? (
          /* Full Interactive FAQ Page */
          <FAQPage
            settings={settings}
            onNavigateHome={handleBackToHome}
            onSelectCategory={(cat) => {
              setPlaceholderView(null);
              handleSelectCategory(cat);
            }}
            onNavigateCalculators={() => handleOpenCalculators()}
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
          />
        ) : placeholderView === "glossary" ? (
          /* Full Interactive Glossary Page */
          <GlossaryPage
            settings={settings}
            onNavigateHome={handleBackToHome}
            onSelectCategory={(cat) => {
              setPlaceholderView(null);
              handleSelectCategory(cat);
            }}
            onNavigateCalculators={() => handleOpenCalculators()}
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
            onSearchChange={setSearchQuery}
            searchQuery={searchQuery}
          />
        ) : (
          /* Interactive Guides Hub, Checklist, or Printable Redemption Page */
          activeGuidePage === "how-to-choose" ? (
            <HowToChooseFundGuide
              settings={settings}
              onNavigateHome={handleBackToHome}
              onSelectCategory={(cat) => {
                setPlaceholderView(null);
                handleSelectCategory(cat);
              }}
              onNavigateCalculators={() => handleOpenCalculators()}
              onNavigateFAQ={handleNavigateFAQ}
              onNavigateGlossary={handleNavigateGlossary}
              onNavigateGuides={() => handleNavigateGuides("index")}
              onNavigateHub={handleNavigateHub}
              onNavigateRedemptionChecklist={() => handleNavigateGuides("redemption")}
              onSearchChange={setSearchQuery}
              searchQuery={searchQuery}
            />
          ) : activeGuidePage === "redemption" ? (
            <RedemptionChecklistPage
              settings={settings}
              onNavigateHome={handleBackToHome}
              onSelectCategory={(cat) => {
                setPlaceholderView(null);
                handleSelectCategory(cat);
              }}
              onNavigateCalculators={() => handleOpenCalculators()}
              onNavigateFAQ={handleNavigateFAQ}
              onNavigateGlossary={handleNavigateGlossary}
              onNavigateGuides={() => handleNavigateGuides("index")}
              onNavigateHowToChooseGuide={() => handleNavigateGuides("how-to-choose")}
              onNavigateHub={handleNavigateHub}
              onSearchChange={setSearchQuery}
              searchQuery={searchQuery}
            />
          ) : (
            <GuidesIndexPage
              settings={settings}
              onNavigateHome={handleBackToHome}
              onSelectCategory={(cat) => {
                setPlaceholderView(null);
                handleSelectCategory(cat);
              }}
              onNavigateCalculators={() => handleOpenCalculators()}
              onNavigateFAQ={handleNavigateFAQ}
              onNavigateGlossary={handleNavigateGlossary}
              onNavigateGuides={() => handleNavigateGuides("index")}
              onNavigateHowToChooseGuide={() => handleNavigateGuides("how-to-choose")}
              onNavigateRedemptionChecklist={() => handleNavigateGuides("redemption")}
              onNavigateHub={handleNavigateHub}
              onSearchChange={setSearchQuery}
              searchQuery={searchQuery}
            />
          )
        )
      ) : isCalculatorView ? (
        activeCalculatorPage === "hub" ? (
          <CalculatorsHubPage
            settings={settings}
            onNavigateHome={handleBackToHome}
            onNavigateCalculators={() => handleOpenCalculators()}
            onNavigateCalculator={(slug) => handleOpenCalculators(slug)}
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
            onSelectCategory={(cat) => {
              setIsCalculatorView(false);
              handleSelectCategory(cat);
            }}
            onSearchChange={setSearchQuery}
            searchQuery={searchQuery}
          />
        ) : activeCalculatorPage === "sip" ? (
          <SipCalculatorPage
            settings={settings}
            onNavigateHome={handleBackToHome}
            onNavigateCalculators={() => handleOpenCalculators()}
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
            onSelectCategory={(cat) => {
              setIsCalculatorView(false);
              handleSelectCategory(cat);
            }}
            onSearchChange={setSearchQuery}
            searchQuery={searchQuery}
          />
        ) : activeCalculatorPage === "step-up-sip" ? (
          <StepUpSipCalculatorPage
            settings={settings}
            onNavigateHome={handleBackToHome}
            onNavigateCalculators={() => handleOpenCalculators()}
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
            onSelectCategory={(cat) => {
              setIsCalculatorView(false);
              handleSelectCategory(cat);
            }}
            onSearchChange={setSearchQuery}
            searchQuery={searchQuery}
          />
        ) : activeCalculatorPage === "lumpsum" ? (
          <LumpsumCalculatorPage
            settings={settings}
            onNavigateHome={handleBackToHome}
            onNavigateCalculators={() => handleOpenCalculators()}
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
            onSelectCategory={(cat) => {
              setIsCalculatorView(false);
              handleSelectCategory(cat);
            }}
            onSearchChange={setSearchQuery}
            searchQuery={searchQuery}
          />
        ) : activeCalculatorPage === "swp" ? (
          <SwpCalculatorPage
            settings={settings}
            onNavigateHome={handleBackToHome}
            onNavigateCalculators={() => handleOpenCalculators()}
            onNavigateCalculator={(target) => handleOpenCalculators(target)}
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
            onSelectCategory={(cat) => {
              setIsCalculatorView(false);
              handleSelectCategory(cat);
            }}
            onSearchChange={setSearchQuery}
            searchQuery={searchQuery}
          />
        ) : activeCalculatorPage === "goal-planner" ? (
          <GoalPlannerCalculatorPage
            settings={settings}
            onNavigateHome={handleBackToHome}
            onNavigateCalculators={() => handleOpenCalculators()}
            onNavigateCalculator={(target) => handleOpenCalculators(target)}
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
            onSelectCategory={(cat) => {
              setIsCalculatorView(false);
              handleSelectCategory(cat);
            }}
            onSearchChange={setSearchQuery}
            searchQuery={searchQuery}
          />
        ) : activeCalculatorPage === "tax-estimator" ? (
          <TaxEstimatorCalculatorPage
            settings={settings}
            onNavigateHome={handleBackToHome}
            onNavigateCalculators={() => handleOpenCalculators()}
            onNavigateCalculator={(target) => handleOpenCalculators(target)}
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
            onSelectCategory={(cat) => {
              setIsCalculatorView(false);
              handleSelectCategory(cat);
            }}
            onSearchChange={setSearchQuery}
            searchQuery={searchQuery}
          />
        ) : (
          /* Dedicated Calculators Suite Page */
          <>
            <Navbar
              currentCategory={currentCategory}
              onSelectCategory={(cat) => {
                setIsCalculatorView(false);
                handleSelectCategory(cat);
              }}
              onSearchChange={setSearchQuery}
              searchQuery={searchQuery}
              settings={settings}
              onNavigateHome={handleBackToHome}
              isCalculatorView={true}
              onNavigateCalculators={() => handleOpenCalculators()}
              activeMenu="calculators"
              onNavigateFAQ={handleNavigateFAQ}
              onNavigateGlossary={handleNavigateGlossary}
              onNavigateGuides={handleNavigateGuides}
              onNavigateHubs={() => handleNavigateHub()}
            />

            <main className="flex-1">
              <Suspense fallback={<div className="min-h-screen py-24 text-center text-xs font-mono-data text-stone-500">Loading quantitative calculator suite...</div>}>
                <CalculatorSuitePage
                  onBackToHome={handleBackToHome}
                  onNavigateArticle={handleOpenArticle}
                  allPosts={posts}
                  initialTab={calculatorTab}
                  onTabChange={(tab) => setCalculatorTab(tab)}
                />
              </Suspense>
            </main>

            <Footer
              settings={settings}
              onSelectCategory={(cat) => {
                setIsCalculatorView(false);
                handleSelectCategory(cat);
              }}
              onNavigateCalculators={() => handleOpenCalculators()}
              onNavigateCalculator={handleOpenCalculators}
              onNavigateFAQ={handleNavigateFAQ}
              onNavigateGlossary={handleNavigateGlossary}
              onNavigateGuides={handleNavigateGuides}
              onNavigateHubs={() => handleNavigateHub()}
            />
          </>
        )
      ) : selectedArticle ? (
        /* Single Article View */
        <>
          <Suspense fallback={<div className="min-h-screen py-24 text-center text-xs font-mono-data text-stone-500">Loading research report...</div>}>
            <ArticleReader
              post={selectedArticle}
              onBack={handleBackToHome}
              settings={settings}
              onOpenCategory={(cat) => {
                handleSelectCategory(cat);
              }}
              allPosts={posts}
              onNavigateArticle={handleOpenArticle}
              onNavigateHub={handleNavigateHub}
              onNavigateCalculator={(url) => handleOpenCalculators(url)}
              onNavigateGlossaryTerm={(termId) => {
                handleNavigateGlossary();
                setTimeout(() => {
                  const el = document.getElementById(termId);
                  if (el) el.scrollIntoView({ behavior: "smooth", block: "center" });
                }, 250);
              }}
            />
          </Suspense>
          <Footer
            settings={settings}
            onSelectCategory={handleSelectCategory}
            onNavigateCalculators={() => handleOpenCalculators()}
            onNavigateCalculator={handleOpenCalculators}
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
            onNavigateHubs={() => handleNavigateHub()}
          />
        </>
      ) : (
        /* Blog Main Homepage */
        <>
          <Navbar
            currentCategory={currentCategory}
            onSelectCategory={handleSelectCategory}
            onSearchChange={setSearchQuery}
            searchQuery={searchQuery}
            settings={settings}
            onNavigateHome={handleBackToHome}
            isCalculatorView={false}
            onNavigateCalculators={() => handleOpenCalculators()}
            activeMenu="none"
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
            onNavigateHubs={() => handleNavigateHub()}
          />

          <main className="flex-1 max-w-6xl w-full mx-auto px-4 py-6 sm:py-8 space-y-10">
            {/* Featured Quantitative Calculators Banner */}
            <div className="bg-gradient-to-r from-[#1e293b] via-[#151f30] to-[#0f172a] text-white p-5 sm:p-6 rounded-2xl border border-slate-700/80 shadow-md flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
              <div className="space-y-1.5">
                <div className="inline-flex items-center gap-1.5 text-[10px] font-mono-data uppercase tracking-wider text-emerald-400 font-semibold px-2.5 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20">
                  <Sparkles className="w-3 h-3 text-emerald-400" />
                  <span>Interactive Quantitative Suite</span>
                </div>
                <h2 className="text-lg sm:text-xl font-bold font-serif-editorial text-white">
                  Mutual Fund Interactive Calculators
                </h2>
                <p className="text-slate-300 text-xs sm:text-sm font-sans max-w-xl">
                  Simulate Direct vs Regular TER drag, step-up SIP compounding, procrastination delay costs, and SIP vs lumpsum entry dynamics.
                </p>
              </div>
              <button
                onClick={() => handleOpenCalculators()}
                className="shrink-0 px-4 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs font-mono-data tracking-wide transition-all shadow-md flex items-center gap-2 group cursor-pointer"
              >
                <span>Launch All 4 Calculators</span>
                <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-0.5 transition-transform" />
              </button>
            </div>

            {/* Loading State */}
            {loading ? (
              <div className="py-20 text-center text-xs font-mono-data text-stone-500">
                Loading research index...
              </div>
            ) : filteredPosts.length === 0 ? (
              /* No Search Results */
              <div className="py-16 text-center bg-white rounded-2xl border border-stone-200 p-8 space-y-3">
                <p className="text-sm font-serif-editorial text-stone-700">
                  No mutual fund reports found matching "{searchQuery}".
                </p>
                <button
                  onClick={() => {
                    setSearchQuery("");
                    setCurrentCategory("all");
                  }}
                  className="text-xs text-stone-900 underline font-medium"
                >
                  Clear all filters
                </button>
              </div>
            ) : (
              /* Articles Listing */
              <div className="space-y-12">
                <section>
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                    {filteredPosts.map((post) => (
                      <ArticleCard
                        key={post.id}
                        post={post}
                        onOpen={handleOpenArticle}
                      />
                    ))}
                  </div>
                </section>

                {/* Newsletter Subscription Block */}
                <NewsletterSignup />
              </div>
            )}
          </main>

          <Footer
            settings={settings}
            onSelectCategory={handleSelectCategory}
            onNavigateCalculators={() => handleOpenCalculators()}
            onNavigateCalculator={handleOpenCalculators}
            onNavigateFAQ={handleNavigateFAQ}
            onNavigateGlossary={handleNavigateGlossary}
            onNavigateGuides={handleNavigateGuides}
            onNavigateHubs={() => handleNavigateHub()}
          />
        </>
      )}
    </div>
  );
}
